[build]
  command = "npm install --legacy-peer-deps && NODE_ENV=production npx webpack --mode production"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200